import { readFileSync } from "node:fs";
import { fileURLToPath, URL } from "node:url";
import tailwindcss from "@tailwindcss/vite";
import vue from "@vitejs/plugin-vue";
import { defineConfig, type Plugin } from "vite";

/**
 * Serves the local dev-bridge runtime configuration at /config.json without
 * putting it in public/, because anything in public/ is copied into dist/ and
 * would ship inside the deployed artifact. That matters more than it looks:
 * the dev configuration is a valid document — loopback API, no identity
 * provider — so a deployed console that picked it up would boot cleanly and
 * quietly talk to nothing, rather than failing loudly. The deployed
 * config.json is generated by the CDK stack instead.
 */
const devRuntimeConfig = (): Plugin => ({
  name: "hemlig-dev-runtime-config",
  apply: "serve",
  configureServer(server) {
    server.middlewares.use("/config.json", (_request, response) => {
      const body = readFileSync(
        fileURLToPath(new URL("./dev-config.json", import.meta.url)),
        "utf8",
      );
      response.setHeader("content-type", "application/json");
      response.setHeader("cache-control", "no-store");
      response.end(body);
    });
  },
});

export default defineConfig({
  plugins: [vue(), tailwindcss(), devRuntimeConfig()],
  resolve: {
    alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) },
  },
  build: {
    target: "es2022",
    // The published Content-Security-Policy forbids inline script and style,
    // so nothing may be inlined into index.html or silent.html.
    assetsInlineLimit: 0,
    cssCodeSplit: false,
    sourcemap: false,
    rollupOptions: {
      // silent.html is its own entry point (not reachable via the SPA
      // router) so the renewal iframe never boots the whole app — see
      // src/silent.ts.
      input: {
        main: fileURLToPath(new URL("./index.html", import.meta.url)),
        silent: fileURLToPath(new URL("./silent.html", import.meta.url)),
      },
    },
  },
  server: {
    // Pinned to loopback IPv4 so the dev bridge's CORS origin and the browser
    // agree on one address; "localhost" can resolve to ::1 and mismatch it.
    host: "127.0.0.1",
    port: 5273,
    strictPort: true,
  },
});
