import { ref, type Ref } from "vue";
import { ApiError } from "../api/errors";

export type MutationFamily = "secret" | "consumer";

export type MutationPhase =
  | { readonly kind: "idle" }
  | { readonly kind: "submitting" }
  | { readonly kind: "succeeded" }
  | { readonly kind: "failed"; readonly error: ApiError }
  /** `If-Match` was stale. Never retried automatically; the draft is kept. */
  | { readonly kind: "stale"; readonly error: ApiError }
  /**
   * The request may or may not have been applied and the caller must re-read.
   * Reached on a network failure, 500, 503, or a 409 on a reused key.
   */
  | { readonly kind: "unknown"; readonly error: ApiError; readonly reconciling: boolean }
  /** A reconciliation determined the mutation had in fact been applied. */
  | { readonly kind: "reconciled-applied" }
  /** A reconciliation determined the mutation had not been applied. */
  | { readonly kind: "reconciled-absent"; readonly error: ApiError };

export interface GuardedMutation<TInput, TResult> {
  readonly phase: Ref<MutationPhase>;
  readonly result: Ref<TResult | undefined>;
  submit(input: TInput): Promise<TResult | undefined>;
  /** Retry is only offered where the API replays by idempotency key. */
  readonly canRetry: Ref<boolean>;
  retry(): Promise<TResult | undefined>;
  reset(): void;
}

export interface GuardedMutationOptions<TInput, TResult> {
  readonly family: MutationFamily;
  /**
   * Called once per submit intent. The key is held for the lifetime of that
   * intent and is never regenerated by a re-render, because a fresh key on a
   * retry risks a double write.
   */
  mutate(input: TInput, idempotencyKey: string): Promise<TResult>;
  /**
   * Secret routes only. Re-reads the resource and reports whether the intended
   * mutation landed. Required because those routes hard-conflict on a reused
   * key and never replay the original response, so an ambiguous outcome cannot
   * be resolved by retrying.
   */
  reconcile?(input: TInput): Promise<TResult | undefined>;
  newKey?(): string;
}

const defaultKey = (): string => crypto.randomUUID();

export const useGuardedMutation = <TInput, TResult>(
  options: GuardedMutationOptions<TInput, TResult>,
): GuardedMutation<TInput, TResult> => {
  const phase = ref<MutationPhase>({ kind: "idle" }) as Ref<MutationPhase>;
  const result = ref<TResult | undefined>() as Ref<TResult | undefined>;
  const canRetry = ref(false);
  let pendingKey: string | undefined;
  let pendingInput: TInput | undefined;

  const run = async (input: TInput, key: string): Promise<TResult | undefined> => {
    phase.value = { kind: "submitting" };
    canRetry.value = false;
    try {
      const value = await options.mutate(input, key);
      result.value = value;
      phase.value = { kind: "succeeded" };
      pendingKey = undefined;
      pendingInput = undefined;
      return value;
    } catch (caught) {
      const error =
        caught instanceof ApiError
          ? caught
          : new ApiError(0, "network", "The request did not reach Hemlig.");

      if (error.code === "precondition_failed") {
        // Someone else advanced the control revision. Reloading and
        // resubmitting silently would defeat optimistic concurrency, so the
        // draft is preserved and the decision handed to the administrator.
        phase.value = { kind: "stale", error };
        return undefined;
      }

      const ambiguous = error.outcomeUnknown || error.code === "conflict";
      if (!ambiguous) {
        phase.value = { kind: "failed", error };
        return undefined;
      }

      if (options.family === "consumer") {
        // Consumer enrollment, rotation, and revocation replay the recorded
        // result for a repeated key, so retrying the same key is safe and is
        // the correct response. `enrollment_failed` is terminal and is not
        // ambiguous, so it never reaches here.
        phase.value = { kind: "unknown", error, reconciling: false };
        canRetry.value = true;
        return undefined;
      }

      phase.value = { kind: "unknown", error, reconciling: options.reconcile !== undefined };
      if (options.reconcile === undefined) {
        return undefined;
      }
      try {
        const applied = await options.reconcile(input);
        if (applied === undefined) {
          phase.value = { kind: "reconciled-absent", error };
          return undefined;
        }
        result.value = applied;
        phase.value = { kind: "reconciled-applied" };
        return applied;
      } catch {
        phase.value = { kind: "unknown", error, reconciling: false };
        return undefined;
      }
    }
  };

  return {
    phase,
    result,
    canRetry,
    async submit(input) {
      pendingKey = (options.newKey ?? defaultKey)();
      pendingInput = input;
      return run(input, pendingKey);
    },
    async retry() {
      if (pendingKey === undefined || pendingInput === undefined) {
        return undefined;
      }
      // Deliberately the same key: this path exists only for the route family
      // that replays it.
      return run(pendingInput, pendingKey);
    },
    reset() {
      phase.value = { kind: "idle" };
      result.value = undefined;
      canRetry.value = false;
      pendingKey = undefined;
      pendingInput = undefined;
    },
  };
};
